services:
  mcp_genimage_server:
    build: .
    container_name: mcp_genimage_server
    ports:
      - "8001:8000"
    volumes:
      # Mount the local ./app directory to /app/app inside the container
      # to match the package structure expected by the relative imports.
      - ./app:/app/app
      - ./workflows:/app/workflows
      - ./outputs:/app/outputs
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # The command now targets the 'app' object inside the 'app.main' module.
    # The --reload flag will watch for changes in the mounted volume.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
