"""Add is_visible to RenderType and default render type to Style

Revision ID: 034ad31be73a
Revises: 52df28b234c8
Create Date: 2025-09-20 06:02:00.612000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034ad31be73a'
down_revision: Union[str, Sequence[str], None] = '52df28b234c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.alter_column('recommended_render_type_id', new_column_name='default_render_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.alter_column('default_render_type_id', new_column_name='recommended_render_type_id')

    with op.batch_alter_table('render_types', schema=None) as batch_op:
        batch_op.drop_column('is_visible')
    # ### end Alembic commands ###