"""add_ollama_instance_and_description_settings_tables

Revision ID: 29cfa24f8c15
Revises: cdef50967a00
Create Date: 2025-09-23 09:06:54.363873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29cfa24f8c15'
down_revision: Union[str, Sequence[str], None] = 'cdef50967a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ollama_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ollama_instances_id'), 'ollama_instances', ['id'], unique=False)
    op.create_table('description_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ollama_instance_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('natural_prompt_template_en', sa.Text(), nullable=False),
    sa.Column('optimized_prompt_template_en', sa.Text(), nullable=False),
    sa.Column('natural_prompt_template_fr', sa.Text(), nullable=False),
    sa.Column('optimized_prompt_template_fr', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ollama_instance_id'], ['ollama_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('description_settings')
    op.drop_index(op.f('ix_ollama_instances_id'), table_name='ollama_instances')
    op.drop_table('ollama_instances')
    # ### end Alembic commands ###
