"""add_prompt_generator_models

Revision ID: 2c58dc0fdcde
Revises: 29cfa24f8c15
Create Date: 2025-10-03 09:12:30.092706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c58dc0fdcde'
down_revision: Union[str, Sequence[str], None] = '29cfa24f8c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_generator_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjects_to_propose', sa.Integer(), nullable=False),
    sa.Column('elements_to_propose', sa.Integer(), nullable=False),
    sa.Column('elements_to_select', sa.Integer(), nullable=False),
    sa.Column('variations_to_propose', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_generator_allowed_styles',
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('style_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_generator_allowed_styles')
    op.drop_table('prompt_generator_settings')
    # ### end Alembic commands ###
