"""Add m2m relationship between ComfyUI instances and Render Types

Revision ID: 52df28b234c8
Revises: 53389da8ab22
Create Date: 2025-09-18 19:37:27.468148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52df28b234c8'
down_revision: Union[str, Sequence[str], None] = '53389da8ab22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comfyui_render_type_association',
    sa.Column('comfyui_instance_id', sa.Integer(), nullable=False),
    sa.Column('render_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comfyui_instance_id'], ['comfyui_instances.id'], ),
    sa.ForeignKeyConstraint(['render_type_id'], ['render_types.id'], ),
    sa.PrimaryKeyConstraint('comfyui_instance_id', 'render_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comfyui_render_type_association')
    # ### end Alembic commands ###
