"""Add is_default column to Style model

Revision ID: 53389da8ab22
Revises: fe1e90be41e2
Create Date: 2025-09-15 19:26:49.335886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53389da8ab22'
down_revision: Union[str, Sequence[str], None] = 'fe1e90be41e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('styles', sa.Column('is_default', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('styles', 'is_default')
    # ### end Alembic commands ###