"""add_generation_mode_to_rendertype_and_update_seed_type

Revision ID: 685351c0ae09
Revises: 034ad31be73a
Create Date: 2025-09-21 19:44:09.404717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685351c0ae09'
down_revision: Union[str, Sequence[str], None] = '034ad31be73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.alter_column('seed',
            existing_type=sa.VARCHAR(),
            type_=sa.BigInteger(),
            existing_nullable=True)

    op.add_column('render_types', sa.Column('generation_mode', sa.String(length=50), server_default='image_generation', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('render_types', 'generation_mode')
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.alter_column('seed',
            existing_type=sa.BigInteger(),
            type_=sa.VARCHAR(),
            existing_nullable=True)
    # ### end Alembic commands ###