"""replace_is_default_with_mode_specific_defaults

Revision ID: cdef50967a00
Revises: 685351c0ae09
Create Date: 2025-09-21 22:00:53.893154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdef50967a00'
down_revision: Union[str, Sequence[str], None] = '685351c0ae09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default_for_generation', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_default_for_upscale', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.drop_column('is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=False, server_default='0'))
        batch_op.drop_column('is_default_for_upscale')
        batch_op.drop_column('is_default_for_generation')
    # ### end Alembic commands ###