"""Initial schema creation

Revision ID: fe1e90be41e2
Revises: 
Create Date: 2025-09-15 15:20:02.789781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1e90be41e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comfyui_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_comfyui_instances_id'), 'comfyui_instances', ['id'], unique=False)
    op.create_table('render_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('workflow_filename', sa.String(), nullable=False),
    sa.Column('prompt_examples', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_types_id'), 'render_types', ['id'], unique=False)
    op.create_index(op.f('ix_render_types_name'), 'render_types', ['name'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('positive_prompt', sa.String(), nullable=False),
    sa.Column('negative_prompt', sa.String(), nullable=False),
    sa.Column('render_type_name', sa.String(), nullable=True),
    sa.Column('style_names', sa.String(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('seed', sa.String(), nullable=True),
    sa.Column('llm_enhanced', sa.Boolean(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('comfyui_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comfyui_instance_id'], ['comfyui_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_id'), 'generation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_logs_status'), 'generation_logs', ['status'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=False),
    sa.Column('negative_prompt_template', sa.String(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recommended_render_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recommended_render_type_id'], ['render_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_styles_category'), 'styles', ['category'], unique=False)
    op.create_index(op.f('ix_styles_id'), 'styles', ['id'], unique=False)
    op.create_index(op.f('ix_styles_name'), 'styles', ['name'], unique=True)
    op.create_table('style_render_type_association',
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('render_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['render_type_id'], ['render_types.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('style_id', 'render_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_render_type_association')
    op.drop_index(op.f('ix_styles_name'), table_name='styles')
    op.drop_index(op.f('ix_styles_id'), table_name='styles')
    op.drop_index(op.f('ix_styles_category'), table_name='styles')
    op.drop_table('styles')
    op.drop_index(op.f('ix_generation_logs_status'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_id'), table_name='generation_logs')
    op.drop_table('generation_logs')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_render_types_name'), table_name='render_types')
    op.drop_index(op.f('ix_render_types_id'), table_name='render_types')
    op.drop_table('render_types')
    op.drop_index(op.f('ix_comfyui_instances_id'), table_name='comfyui_instances')
    op.drop_table('comfyui_instances')
    # ### end Alembic commands ###
